fix

diff --git a/bin/hawq b/bin/hawq
--- a/bin/hawq
+++ b/bin/hawq
@@ -1,3 +1,7 @@
 #!/bin/bash
+if [[ ! -f /usr/local/hawq/greenplum_path.sh ]]; then
+  echo 'hawq not found in /usr/local/hawq/'
+  exit 1
+fi
 source /usr/local/hawq/greenplum_path.sh
 exec hawq $@
