fix

diff --git a/config/bashrc b/config/bashrc
--- a/config/bashrc
+++ b/config/bashrc
@@ -22,6 +22,11 @@ if [ $system == Darwin ]; then
   yzy_NPROC=`sysctl -n hw.ncpu`
   yzy_CORE_DIR=$(dirname $(sysctl -n kern.corefile))
 fi
+trap 'echo -e "\033[31mERR $? in \033[1m${FUNCNAME-bash}: $BASH_COMMAND \033[0m"' ERR
+error() {
+  echo -e "\033[31m$@\033[0m"
+}
+
 HAWQ_SRC=~/dev/hawq
 HORNET_SRC=~/dev/hornet
 hornet_src_dir=~/dev/hornet/
@@ -167,6 +172,14 @@ lava-clean() {
 #   Hawq 
 #
 #-------------------------------------------------------------------------------
+alias hawq-config='hawq-config.py'
+hawq-config-deprecated() {
+  if [[ $# -eq 1 ]]; then
+    hawq config --show $1
+  else
+    hawq config --skipvalidation --change $1 --value $2
+  fi
+}
 hawq-qe() {
   if [ -n "$1" ]; then
     ps -eo pid,command| grep [p]ostgres.*con.*seg| awk '{print $1}' |
@@ -224,16 +237,8 @@ magma-init() {
   rm -rf ${yzy_CORE_DIR}/core*
   hawq-restart
 }
-hawq-config() {
-  hawq-config.py "$@"
-  return
-  if [[ $# -eq 1 ]]; then
-    hawq config --show $1
-  else
-    hawq config --skipvalidation --change $1 --value $2
-  fi
-}
-hawq-init() {
+hawq-init() {(
+  set -ex
   num=${1-4}
   rm -rf ${yzy_CORE_DIR}/core*
   hawq-stop
@@ -248,7 +253,6 @@ hawq-init() {
   hawq-config hawq_master_directory $hawq_master_directory
   hawq-config hawq_segment_directory $hawq_segment_directory
 
-  set -ex
   sudo rm -rf $hawq_magma_locations_master
   sudo rm -rf $hawq_magma_locations_segment
   sudo rm -rf $hawq_master_directory
@@ -257,13 +261,12 @@ hawq-init() {
   sudo install -o $USER -d $hawq_magma_locations_segment
   sudo install -o $USER -d $hawq_master_directory
   sudo install -o $USER -d $hawq_segment_directory
-  set +ex
   hawq init cluster -a --locale='C' --lc-collate='C' \
         --lc-ctype='C' --lc-messages='C' \
         --lc-monetary='C' --lc-numeric='C' \
         --lc-time='C'
   hawq-setup-feature-test && rm -rf ~/hawqAdminLogs
-}
+)}
 hawq-stop() {
   ps -eo pid,command | grep -E '^ *[0-9]+ [^ ]*postgres' | awk '{print $1}' | xargs sudo kill -9
   ps -eo pid,command | grep -E '^ *[0-9]+ [^ ]*magma_server' | awk '{print $1}' | xargs sudo kill -9
@@ -389,9 +392,9 @@ hornet-coverage-report() {
   parse_lcov_output.py ${hornet_src_dir} ${hornet_cov_dir}/CodeCoverage.info.cleaned
   # '*/test/unit/*' '*/testutil/*' \
 }
-hornet-coverage() {
-  test $# -gt 2 && echo 'Error number of arguments.'
+hornet-coverage() {(
   set -e
+  test $# -gt 2 && error 'Invalid number of arguments.' && return 1
   if [[ $# -eq 0 || $# -eq 2 ]]; then
     if [[ $# -eq 2 ]]; then
       hornet_src_dir=$1
@@ -414,7 +417,10 @@ hornet-coverage() {
     interconnect);;
     storage);;
     executor);;
-    *) return;;
+    *)
+      error Invalid component $1 
+      return 1
+    ;;
   esac
   # hornet-debug
   hornet-coverage-setup
@@ -426,8 +432,7 @@ hornet-coverage() {
   make resetcoverage
   make punittest
   gen-coverage
-  set +e
-}
+)}
 hornet-test() {
   if [ -n "$1" ]; then
     if [[ `pwd` =~ "magma" ]]; then
@@ -536,7 +541,6 @@ then
   PS1=$PS1'`__git_ps1 " (%s)"`'
 fi
                                                            # last command status
-export PS1='`s=$? && test $s -ne 0 && echo \[\033[31mExit code is $s`'$PS1
 export PS1=$PS1'\n\[\033[01m\]\$ \[\033[00m\]'                      # UID symbol
 
 export LS_COLORS="rs=0:di=38;5;27:ln=38;5;51:mh=44;38;5;15:pi=40;38;5;11:so=38;5;13:do=38;5;5:bd=48;5;232;38;5;11:cd=48;5;232;38;5;3:or=48;5;232;38;5;9:mi=05;48;5;232;38;5;15:su=48;5;196;38;5;15:sg=48;5;11;38;5;16:ca=48;5;196;38;5;226:tw=48;5;10;38;5;16:ow=48;5;10;38;5;21:st=48;5;21;38;5;15:ex=38;5;34:*.tar=38;5;9:*.tgz=38;5;9:*.arc=38;5;9:*.arj=38;5;9:*.taz=38;5;9:*.lha=38;5;9:*.lz4=38;5;9:*.lzh=38;5;9:*.lzma=38;5;9:*.tlz=38;5;9:*.txz=38;5;9:*.tzo=38;5;9:*.t7z=38;5;9:*.zip=38;5;9:*.z=38;5;9:*.Z=38;5;9:*.dz=38;5;9:*.gz=38;5;9:*.lrz=38;5;9:*.lz=38;5;9:*.lzo=38;5;9:*.xz=38;5;9:*.bz2=38;5;9:*.bz=38;5;9:*.tbz=38;5;9:*.tbz2=38;5;9:*.tz=38;5;9:*.deb=38;5;9:*.rpm=38;5;9:*.jar=38;5;9:*.war=38;5;9:*.ear=38;5;9:*.sar=38;5;9:*.rar=38;5;9:*.alz=38;5;9:*.ace=38;5;9:*.zoo=38;5;9:*.cpio=38;5;9:*.7z=38;5;9:*.rz=38;5;9:*.cab=38;5;9:*.jpg=38;5;13:*.jpeg=38;5;13:*.gif=38;5;13:*.bmp=38;5;13:*.pbm=38;5;13:*.pgm=38;5;13:*.ppm=38;5;13:*.tga=38;5;13:*.xbm=38;5;13:*.xpm=38;5;13:*.tif=38;5;13:*.tiff=38;5;13:*.png=38;5;13:*.svg=38;5;13:*.svgz=38;5;13:*.mng=38;5;13:*.pcx=38;5;13:*.mov=38;5;13:*.mpg=38;5;13:*.mpeg=38;5;13:*.m2v=38;5;13:*.mkv=38;5;13:*.webm=38;5;13:*.ogm=38;5;13:*.mp4=38;5;13:*.m4v=38;5;13:*.mp4v=38;5;13:*.vob=38;5;13:*.qt=38;5;13:*.nuv=38;5;13:*.wmv=38;5;13:*.asf=38;5;13:*.rm=38;5;13:*.rmvb=38;5;13:*.flc=38;5;13:*.avi=38;5;13:*.fli=38;5;13:*.flv=38;5;13:*.gl=38;5;13:*.dl=38;5;13:*.xcf=38;5;13:*.xwd=38;5;13:*.yuv=38;5;13:*.cgm=38;5;13:*.emf=38;5;13:*.axv=38;5;13:*.anx=38;5;13:*.ogv=38;5;13:*.ogx=38;5;13:*.aac=38;5;45:*.au=38;5;45:*.flac=38;5;45:*.mid=38;5;45:*.midi=38;5;45:*.mka=38;5;45:*.mp3=38;5;45:*.mpc=38;5;45:*.ogg=38;5;45:*.ra=38;5;45:*.wav=38;5;45:*.axa=38;5;45:*.oga=38;5;45:*.spx=38;5;45:*.xspf=38;5;45:"
